# Generated by Django 2.2.15 on 2022-12-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='condition',
            field=models.CharField(choices=[('Nowy', 'Nowy'), ('Używany', 'Używany'), ('Uszkodzony', 'Uszkodzony')], max_length=100),
        ),
    ]
