# Generated by Django 2.2.15 on 2022-12-21 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_city_province_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adsimages',
            options={'verbose_name_plural': 'Ads Images'},
        ),
    ]
