# Generated by Django 2.2.15 on 2022-12-21 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_auto_20221221_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='province_id',
        ),
    ]
