# Generated by Django 2.2.15 on 2022-12-28 18:01

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_remove_city_province_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='description',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
